### ISSUE TITLE
Periscope Design Changes Made in Figma

### ISSUE THREAD

**Issue by bcechol** [Cryptonomic/periscope#8]
**Homepage**
- [x] Update header in the top left so it is less cramped: [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=829:2972#40459441)
- [x] Add Tezos Network Overview as a side nav item: [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=829:2972#39786964)

**Accounts **
- [x] Title should be top accounts by balance: [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=829:4495#40459512)
- [x] Update x-axis : [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=829:4495#40459537)
> **Dev tasks**
- [ ] below 50 queries label individually. (e.g. 1 2 3 4 5...): [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=851:3719#40459565)
- [ ]  above 50 label by 10s I.e. 10, 20, 30, 40, 50 (skip numbering the notches in between) .
- [ ] Above 500 label by 100   Bakers.

**Bakers**
- [x] Bakers data labeled as “Top Bakers by Stake”: [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=851:3719#40459593)
- [x] Add XTZ unit in all tooltips and remove the full title from them (I.e. it doesn’t need “per hour,” just the unit: [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=851:3719#40459622)
- [ ] Any graph with a date selection needs a legend stating which dates are being displayed
> **Dev tasks**
- [ ] The tooltips should be consistent with which axis is on top and bottom. In the bakers per block it is reversed from the others

**Contacts  **
> **Dev tasks**
- [ ] Same x axis logic as accounts
- [ ] Top contracts by invocation by month shouldn’t be a line chart
- [ ] Needs an x axis that shows hour notches for days, day notches for week, and week notches for month.

**Blocks  **
- [x] Same UI as other graphs
- [x] Needs an x axis that shows hour notches for days, day notches for week, and week notches for month: [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=906:493#40459687)

**Operations **
- [x] same x axis logic as blocks and contracts.

**All**
- [x] Update x-axis to start at 1, not 0: [figma](https://www.figma.com/file/dBCVXPSPpmzEI6cSfuM0D4?node-id=829:2972#40459739)
